-- MySQL Script generated by MySQL Workbench
-- Sun May  2 21:42:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NCMS_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NCMS_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NCMS_DB` DEFAULT CHARACTER SET utf8 ;
USE `NCMS_DB` ;

-- -----------------------------------------------------
-- Table `NCMS_DB`.`Citizen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Citizen` (
  `Serial_Number` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Severity` VARCHAR(45) NOT NULL,
  `Queue_No` INT NULL,
  `Email_Address` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `X_Coordinate` INT NOT NULL,
  `Y_Coordinate` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Mobile_No` INT NULL,
  `Relative_Name` VARCHAR(45) NULL,
  `Relative_Mobile` INT NULL,
  `Relative_Geo_Co` VARCHAR(45) NULL,
  `Register_Date` DATE NOT NULL,
  PRIMARY KEY (`Serial_Number`),
  UNIQUE INDEX `Serial_Number_UNIQUE` (`Serial_Number` ASC) VISIBLE,
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`District` (
  `Name` VARCHAR(45) NOT NULL,
  `X1` INT NOT NULL,
  `X2` INT NOT NULL,
  `Y1` INT NOT NULL,
  `Y2` INT NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Hospital` (
  `Name` VARCHAR(45) NOT NULL,
  `X_Coordinate` INT NOT NULL,
  `Y_Coordinate` INT NOT NULL,
  `District_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `X_Coordinate_UNIQUE` (`X_Coordinate` ASC) VISIBLE,
  UNIQUE INDEX `Y_Coordinate_UNIQUE` (`Y_Coordinate` ASC) VISIBLE,
  INDEX `fk_Hospital_District1_idx` (`District_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_District1`
    FOREIGN KEY (`District_Name`)
    REFERENCES `NCMS_DB`.`District` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`Bed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Bed` (
  `Bed_Status` VARCHAR(45) NOT NULL,
  `Bed_Number` INT NOT NULL,
  `Citizen_Serial_Number` INT NOT NULL,
  `Hospital_Name` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Citizen_Serial_Number_UNIQUE` (`Citizen_Serial_Number` ASC),
  CONSTRAINT `fk_Bed_Citizen1`
    FOREIGN KEY (`Citizen_Serial_Number`)
    REFERENCES `NCMS_DB`.`Citizen` (`Serial_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bed_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `NCMS_DB`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Doctor` (
  `MBBS_No` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email_Address` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Hospital_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MBBS_No`),
  UNIQUE INDEX `MBBS_No_UNIQUE` (`MBBS_No` ASC) VISIBLE,
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC) VISIBLE,
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_Name` ASC) VISIBLE,
  UNIQUE INDEX `Hospital_Name_UNIQUE` (`Hospital_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `NCMS_DB`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`MoH_Authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`MoH_Authority` (
  `Email_Address` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email_Address`),
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Admin` (
  `Email_Address` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email_Address`),
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`MoH_Authority_has_District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`MoH_Authority_has_District` (
  `MoH_Authority_Email_Address` VARCHAR(45) NOT NULL,
  `District_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MoH_Authority_Email_Address`, `District_Name`),
  INDEX `fk_MoH_Authority_has_District_District1_idx` (`District_Name` ASC) VISIBLE,
  INDEX `fk_MoH_Authority_has_District_MoH_Authority1_idx` (`MoH_Authority_Email_Address` ASC) VISIBLE,
  CONSTRAINT `fk_MoH_Authority_has_District_MoH_Authority1`
    FOREIGN KEY (`MoH_Authority_Email_Address`)
    REFERENCES `NCMS_DB`.`MoH_Authority` (`Email_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MoH_Authority_has_District_District1`
    FOREIGN KEY (`District_Name`)
    REFERENCES `NCMS_DB`.`District` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`Admin_has_District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Admin_has_District` (
  `Admin_Email_Address` VARCHAR(45) NOT NULL,
  `District_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Admin_Email_Address`, `District_Name`),
  INDEX `fk_Admin_has_District_District1_idx` (`District_Name` ASC) VISIBLE,
  INDEX `fk_Admin_has_District_Admin1_idx` (`Admin_Email_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_has_District_Admin1`
    FOREIGN KEY (`Admin_Email_Address`)
    REFERENCES `NCMS_DB`.`Admin` (`Email_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_has_District_District1`
    FOREIGN KEY (`District_Name`)
    REFERENCES `NCMS_DB`.`District` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NCMS_DB`.`Admin_has_MoH_Authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NCMS_DB`.`Admin_has_MoH_Authority` (
  `Admin_Email_Address` VARCHAR(45) NOT NULL,
  `MoH_Authority_Email_Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Admin_Email_Address`, `MoH_Authority_Email_Address`),
  INDEX `fk_Admin_has_MoH_Authority_MoH_Authority1_idx` (`MoH_Authority_Email_Address` ASC) VISIBLE,
  INDEX `fk_Admin_has_MoH_Authority_Admin1_idx` (`Admin_Email_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_has_MoH_Authority_Admin1`
    FOREIGN KEY (`Admin_Email_Address`)
    REFERENCES `NCMS_DB`.`Admin` (`Email_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_has_MoH_Authority_MoH_Authority1`
    FOREIGN KEY (`MoH_Authority_Email_Address`)
    REFERENCES `NCMS_DB`.`MoH_Authority` (`Email_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
